version: '3.8'

name: g2b

services:
  mysql:
    container_name: g2b-mysql
    build:
      context: ./mysql
      dockerfile: dockerfile
    ports:
      - 33062:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/log:/var/log/mysql
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/disk:/disk
    restart: unless-stopped
    networks:
      - g2b

networks:
  g2b:
    driver: bridge
