name: deploy

on:
  push:
    branches: ['master']
    paths: ['package.json']

jobs:
  version:
    runs-on: ubuntu-22.04
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      changed: ${{ steps.version.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: version
        run: |
          previous=$(git show HEAD^:package.json | grep '"version"' | awk -F '"' '{print $4}')
          current=$(git show HEAD:package.json | grep '"version"' | awk -F '"' '{print $4}')
          changed=$( [ "$previous" = "$current" ] && echo "false" || echo "true" )
          echo "tag=v$current" >> $GITHUB_OUTPUT
          echo "changed=$changed" >> $GITHUB_OUTPUT

  tagging:
    needs: version
    runs-on: ubuntu-22.04
    if: needs.version.outputs.changed == 'true'
    outputs:
      tag: ${{ needs.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - id: tag
        run: |
          tag=${{ needs.version.outputs.tag }}
          git tag $tag
          git push origin $tag

  build:
    needs: tagging
    runs-on: ubuntu-22.04
    outputs:
      tag: ${{ needs.tagging.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true 
          npm ci
          npm build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  push:
    needs: build
    runs-on: ubuntu-22.04
    env:
      tag: ${{ needs.build.outputs.tag }}
    outputs:
      tag: ${{ needs.build.outputs.tag }}
      registry: ${{ steps.ecr.outputs.registry }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - id: ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: echo "${{ secrets.ENVS }}" >> .env
      - env:
          registry: ${{ steps.ecr.outputs.registry }}
          repository: ${{ secrets.AWS_ECR_REPOSITORY }}
        run: |
          image=$registry/$repository:$tag
          docker build -t $image .
          docker push $image

  deploy:
    needs: push
    runs-on: ubuntu-22.04
    env:
      sha: ${{ github.sha }}
      bucket: ${{secrets.AWS_S3_BUCKET }}
      repository: ${{ secrets.AWS_ECR_REPOSITORY }}
      registry: ${{ needs.push.outputs.registry }}
      tag: ${{ needs.push.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: |
          echo "tag=$tag" >> manifest
          echo "registry=$registry" >> manifest
          echo "repository=$repository" >> manifest
          cp manifest appspec/manifest
      - run: |
          aws deploy push \
            --application-name g2b-server \
            --s3-location s3://$bucket/g2b-server-$tag-$sha.zip \
            --source appspec
      - run: |
          aws deploy create-deployment \
            --application-name g2b-server \
            --deployment-group-name product \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=$bucket,bundleType=zip,key=g2b-server-$tag-$sha.zip
