name: Environments

on: workflow_dispatch

jobs:
  send_to_slack:
    runs-on: ubuntu-22.04

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      ENVS: ${{ secrets.ENVS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Send to slack
        run: |
          sh scripts/send-env-to-slack.sh "production" "$SLACK_WEBHOOK_URL" "$ENVS"
